[package]
name = "myia"
version = "0.1.0"
authors = ["Arnaud Bergeron <abergeron@gmail.com>"]

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.11.1"

[features]
default = ["pyo3/extension-module"]
